[package]
name = "omacal"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "omacal_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde.workspace = true
serde_json.workspace = true
toml = "1"
tracing.workspace = true
omacal-core = { version = "0.1.0", path = "../crates/omacal-core" }
omacal-store = { version = "0.1.0", path = "../crates/omacal-store" }
omacal-google = { version = "0.1.0", path = "../crates/omacal-google" }
omacal-sync = { version = "0.1.0", path = "../crates/omacal-sync" }
jiff = "0.2.35"
keyring = "4.1.6"
open = "5.4.0"
tracing-subscriber = "0.3.23"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "time"] }
anyhow.workspace = true

