[package]
name = "omacal-caldav"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
jiff = "0.2.35"
reqwest = { version = "0.12", features = ["rustls-tls"], default-features = false }
roxmltree = "0.20"
url = "2"

[dev-dependencies]
wiremock = "0.6"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
